<Project Sdk="Microsoft.NET.Sdk">
  
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>b2d1f3a5-7890-4abc-def1-23456789abcd</UserSecretsId>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="8.2.2" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="8.2.2" />
    <PackageReference Include="Aspire.Hosting.NATS" Version="8.0.0" />
    <PackageReference Include="Aspire.NATS.Net" Version="8.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\WebApi\WebApi.csproj" />
    <ProjectReference Include="..\DataGenerator\DataGenerator.csproj" />
  </ItemGroup>
  

</Project>